server:
  port: 5555

spring:
  session:
    store-type: redis  
      
zuul:
  #ignored-services: '*'
  #prefix: /api
  sensitive-headers: 
  routes:
    dogs-by-address:
      path: /dogs-by-address/**
      url: http://localhost:8081/
    dogs-by-service:
      path: /dogs-by-service/**
      serviceId: dogs-frontend
    dogs-frontend: /dogs/**   
    customers-by-address:
      path: /customers-by-address/**
      url: http://localhost:8080/
    customers-by-service:
      path: /customers-by-service/**
      serviceId: customers-frontend
    customers-frontend: /customers/**   
     
     
